name: rwkvmusic
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1


environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  webview_windows: ^0.4.0
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  cookie_jar: ^4.0.8
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info: 
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  event_bus: ^2.0.0
  flutter_blue: ^0.8.0
  flutter_cache_manager: null
  flutter_easyloading: ^3.0.3
  flutter_inappwebview: ^6.0.0
  webview_dart: ^1.0.1
  flutter_localization: ^0.2.0
  flutter_midi_command: ^0.4.15
  flutter_midi_command_platform_interface: ^0.4.1
  # flutter_midi_command_linux: ^0.3.0
  flutter_midi_command_windows: ^0.0.1-dev.9

  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.2.4
  get: ^4.1.4
  intl: ^0.18.1
  kumi_popup_window: ^2.0.1
  loading_animations: ^2.2.0
  on_popup_window_widget: ^0.0.6
  on_process_button_widget: ^2.0.2
  package_info: ^2.0.0
  permission_handler: ^11.3.0
  pull_to_refresh: ^2.0.0
  sentry: ^7.16.1
  share: ^2.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  sqflite_common: null
  uni_links: ^0.5.1
  webview_win_floating: ^2.2.2
  webview_flutter: ^4.0.1
  webview_flutter_plus: ^0.4.4
  # webview_universal: ^0.0.5
  # desktop_webview_window: ^0.2.3
  webview_all: ^0.1.3
  window_manager: ^0.3.8
  flutter_platform_alert: ^0.5.1
  # flutter_gen_runner: ^5.4.0
  # flutter_dialogs: ^3.0.0
  # adaptive_dialog: ^2.1.0
  # custom_alert_dialog_box: ^1.0.2
  # emerge_alert_dialog: ^0.0.3
  # h_alert_dialog: ^1.1.2
  # alert_system: ^0.0.4
  # dropdown_button2: ^2.3.9
  # overlay_support: ^2.1.0
  # flutter_portal: ^1.1.4
  # flutter_platform_alertbox: ^0.0.4
  # quick_blue: ^0.3.1+3
  universal_ble: ^0.9.4
  midi_util: ^1.0.2
  filepicker_windows: ^2.1.0
  group_radio_button: ^1.3.0
  path_provider: ^2.1.2
  archive: ^3.4.10
  # flutter_share: ^2.0.0
  # share_plus: ^8.0.3
  share_extend: ^2.0.0
  just_audio: ^0.9.37
  flutter_svg: ^2.0.10+1
  custom_sliding_segmented_control: ^1.8.2
  flutter_advanced_segment: ^3.0.2
  dropdown_button2: ^2.3.9
  device_info_plus: ^10.1.0


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  msix: ^3.16.7

# msix_config:
#   display_name: RWKV作曲家
#   publisher_display_name: 元始智能
#   identity_name: 9d318136f439.rwkvmusic
#   publisher: CN=0a613623-d143-4979-b772-9d318136f439
#   msix_version: 1.0.4.0
#   logo_path: C:\Users\bay13\RWKVMUSIC\rwkvmusic\assets\images\logo.png
#   store: true
#   signtool_options: /fd sha256 /i "RWKV作曲家" /tr http://timestamp.digicert.com
#   install_certificate: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # plugin:
  #     platforms:
  #       android:
  #         package: com.invisiblewrench.fluttermidicommand
  #         pluginClass: FlutterMidiCommandPlugin
  #       ios:
  #         pluginClass: FlutterMidiCommandPlugin
  #       macos:
  #         pluginClass: SwiftFlutterMidiCommandPlugin
  #       # linux:
  #       #   default_package: flutter_midi_command_linux
        # windows:
        #   default_package: flutter_midi_command_windows
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
     

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fastmodel/
    # - assets/fastmodel/faster_rwkvd.dll
    # - assets/fastmodel/libfaster_rwkvd.so
    # - assets/fastmodel/RWKV-5-ABC-82M-v1-20230901-ctx1024-ncnn.bin
    # - assets/fastmodel/RWKV-5-ABC-82M-v1-20230901-ctx1024-ncnn.config
    # - assets/fastmodel/RWKV-5-ABC-82M-v1-20230901-ctx1024-ncnn.param

    - assets/images/
    - assets/fonts/
    # - assets/sounds/
    - assets/player/soundfont/acoustic_grand_piano-mp3/
    - assets/player/soundfont/acoustic_guitar_steel-mp3/
    - assets/player/soundfont/cello-mp3/
    - assets/player/soundfont/ocarina-mp3/
    - assets/player/soundfont/violin-mp3/
    - assets/icons/
    - assets/piano/
    - assets/piano/assets/
    - assets/doctor/pngList/
    - assets/doctor/static/css/
    - assets/doctor/static/js/
    # - assets/doctor/static/
    - assets/doctor/
    - assets/player/
    # - assets/player/dist/
    - assets/prompts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
