List<String> prompts = [
  "Lost time is never found again",
  "Soft Spring Rain",
  "Happy Waltz",
  "Flower Picking Elf",
  "Babbling Stream",
  "Galloping Steed",
  "Pink Girl Heart",
  "Harmonious Relationship",
  "Mountain Valley",
  "Partner in Crime",
  "Tiptoe Dance",
  "Heroic Story",
  "Breeze Blowing",
  "Celebration Preparation",
  "Hidden Crisis",
  "A calm daily routine",
  "Sudden Shower",
  "Age Of Peace",
  "Recalling the past",
  "Parade welcome",
  "I want to tell you",
  "Plotting",
  "When the clouds part",
  "The Way Home",
  "Harvest Season",
  "Open one's own heart wide",
  "Silent Protection",
  "Joyful Mood",
  "Visit the maternal family",
  "Get away from it all",
];

Map<String,String> soundEffect = {
  "Piano":'acoustic_grand_piano-mp3',
  "Violin":'violin-mp3',
  "Ocarina":'ocarina-mp3',
  "Cello":'cello-mp3',
  "Guitar":'acoustic_guitar_steel-mp3',
};
