import 'dart:core';

import 'automeasure_randomizeabc.dart';

Map<String, Map<String, String>> keytoneToTruetone = {
  'C Major': {},
  'A Minor': {},
  'G Major': {'f': '^f', 'F': '^F'},
  'E Minor': {'f': '^f', 'F': '^F'},
  'D Major': {'f': '^f', 'c': '^c', 'F': '^F', 'C': '^C'},
  'B Minor': {'f': '^f', 'c': '^c', 'F': '^F', 'C': '^C'},
  'A Major': {'f': '^f', 'c': '^c', 'g': '^g', 'F': '^F', 'C': '^C', 'G': '^G'},
  'F# Minor': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'F': '^F',
    'C': '^C',
    'G': '^G'
  },
  'E Major': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D'
  },
  'C# Minor': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D'
  },
  'B Major': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'a': '^a',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D',
    'A': '^A'
  },
  'G# Minor': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'a': '^a',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D',
    'A': '^A'
  },
  'F# Major': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'a': '^a',
    'e': '^e',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D',
    'A': '^A',
    'E': '^E'
  },
  'D# Minor': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'a': '^a',
    'e': '^e',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D',
    'A': '^A',
    'E': '^E'
  },
  'C# Major': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'a': '^a',
    'e': '^e',
    'b': '^b',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D',
    'A': '^A',
    'E': '^E',
    'B': '^B'
  },
  'A# Minor': {
    'f': '^f',
    'c': '^c',
    'g': '^g',
    'd': '^d',
    'a': '^a',
    'e': '^e',
    'b': '^b',
    'F': '^F',
    'C': '^C',
    'G': '^G',
    'D': '^D',
    'A': '^A',
    'E': '^E',
    'B': '^B'
  },
  'F Major': {'b': '_b', 'B': '_B'},
  'D Minor': {'b': '_b', 'B': '_B'},
  'Bb Major': {'b': '_b', 'e': '_e', 'B': '_B', 'E': '_E'},
  'A# Major': {'b': '_b', 'e': '_e', 'B': '_B', 'E': '_E'},
  'G Minor': {'b': '_b', 'e': '_e', 'B': '_B', 'E': '_E'},
  'Eb Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'B': '_B',
    'E': '_E',
    'A': '_A'
  },
  'D# Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'B': '_B',
    'E': '_E',
    'A': '_A'
  },
  'C Minor': {'b': '_b', 'e': '_e', 'a': '_a', 'B': '_B', 'E': '_E', 'A': '_A'},
  'Ab Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D'
  },
  'G# Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D'
  },
  'F Minor': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D'
  },
  'Db Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'g': '_g',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D',
    'G': '_G'
  },
  'Bb Minor': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'g': '_g',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D',
    'G': '_G'
  },
  'Gb Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'g': '_g',
    'c': '_c',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D',
    'G': '_G',
    'C': '_C'
  },
  'Eb Minor': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'g': '_g',
    'c': '_c',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D',
    'G': '_G',
    'C': '_C'
  },
  'Cb Major': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'g': '_g',
    'c': '_c',
    'f': '_f',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D',
    'G': '_G',
    'C': '_C',
    'F': '_F'
  },
  'Ab Minor': {
    'b': '_b',
    'e': '_e',
    'a': '_a',
    'd': '_d',
    'g': '_g',
    'c': '_c',
    'f': '_f',
    'B': '_B',
    'E': '_E',
    'A': '_A',
    'D': '_D',
    'G': '_G',
    'C': '_C',
    'F': '_F'
  },
};
Map<String, Map<String, String>> truetoneToKeytone = {
  'C Major': {},
  'A Minor': {},
  'G Major': {'^f': 'f', '^F': 'F', 'f': '=f', 'F': '=F'},
  'E Minor': {'^f': 'f', '^F': 'F', 'f': '=f', 'F': '=F'},
  'D Major': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C'
  },
  'B Minor': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C'
  },
  'A Major': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G'
  },
  'F# Minor': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G'
  },
  'E Major': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D'
  },
  'C# Minor': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D'
  },
  'B Major': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    '^a': 'a',
    '^A': 'A',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D',
    'a': '=a',
    'A': '=A'
  },
  'G# Minor': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    '^a': 'a',
    '^A': 'A',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D',
    'a': '=a',
    'A': '=A'
  },
  'F# Major': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    '^a': 'a',
    '^A': 'A',
    '^e': 'e',
    '^E': 'E',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D',
    'a': '=a',
    'A': '=A',
    'e': '=e',
    'E': '=E'
  },
  'D# Minor': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    '^a': 'a',
    '^A': 'A',
    '^e': 'e',
    '^E': 'E',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D',
    'a': '=a',
    'A': '=A',
    'e': '=e',
    'E': '=E'
  },
  'C# Major': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    '^a': 'a',
    '^A': 'A',
    '^e': 'e',
    '^E': 'E',
    '^b': 'b',
    '^B': 'B',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D',
    'a': '=a',
    'A': '=A',
    'e': '=e',
    'E': '=E',
    'b': '=b',
    'B': '=B'
  },
  'A# Minor': {
    '^f': 'f',
    '^F': 'F',
    '^c': 'c',
    '^C': 'C',
    '^g': 'g',
    '^G': 'G',
    '^d': 'd',
    '^D': 'D',
    '^a': 'a',
    '^A': 'A',
    '^e': 'e',
    '^E': 'E',
    '^b': 'b',
    '^B': 'B',
    'f': '=f',
    'F': '=F',
    'c': '=c',
    'C': '=C',
    'g': '=g',
    'G': '=G',
    'd': '=d',
    'D': '=D',
    'a': '=a',
    'A': '=A',
    'e': '=e',
    'E': '=E',
    'b': '=b',
    'B': '=B'
  },
  'F Major': {'_b': 'b', '_B': 'B', 'b': '=b', 'B': '=B'},
  'D Minor': {'_b': 'b', '_B': 'B', 'b': '=b', 'B': '=B'},
  'Bb Major': {
    '_b': 'b',
    '_e': 'e',
    '_B': 'B',
    '_E': 'E',
    'b': '=b',
    'e': '=e',
    'B': '=B',
    'E': '=E'
  },
  'A# Major': {
    '_b': 'b',
    '_e': 'e',
    '_B': 'B',
    '_E': 'E',
    'b': '=b',
    'e': '=e',
    'B': '=B',
    'E': '=E'
  },
  'G Minor': {
    '_b': 'b',
    '_e': 'e',
    '_B': 'B',
    '_E': 'E',
    'b': '=b',
    'e': '=e',
    'B': '=B',
    'E': '=E'
  },
  'Eb Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'B': '=B',
    'E': '=E',
    'A': '=A'
  },
  'D# Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'B': '=B',
    'E': '=E',
    'A': '=A'
  },
  'C Minor': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'B': '=B',
    'E': '=E',
    'A': '=A'
  },
  'Ab Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D'
  },
  'G# Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D'
  },
  'F Minor': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D'
  },
  'Db Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_g': 'g',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    '_G': 'G',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'g': '=g',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D',
    'G': '=G'
  },
  'Bb Minor': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_g': 'g',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    '_G': 'G',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'g': '=g',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D',
    'G': '=G'
  },
  'Gb Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_g': 'g',
    '_c': 'c',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    '_G': 'G',
    '_C': 'C',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'g': '=g',
    'c': '=c',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D',
    'G': '=G',
    'C': '=C'
  },
  'Eb Minor': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_g': 'g',
    '_c': 'c',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    '_G': 'G',
    '_C': 'C',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'g': '=g',
    'c': '=c',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D',
    'G': '=G',
    'C': '=C'
  },
  'Cb Major': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_g': 'g',
    '_c': 'c',
    '_f': 'f',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    '_G': 'G',
    '_C': 'C',
    '_F': 'F',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'g': '=g',
    'c': '=c',
    'f': '=f',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D',
    'G': '=G',
    'C': '=C',
    'F': '=F'
  },
  'Ab Minor': {
    '_b': 'b',
    '_e': 'e',
    '_a': 'a',
    '_d': 'd',
    '_g': 'g',
    '_c': 'c',
    '_f': 'f',
    '_B': 'B',
    '_E': 'E',
    '_A': 'A',
    '_D': 'D',
    '_G': 'G',
    '_C': 'C',
    '_F': 'F',
    'b': '=b',
    'e': '=e',
    'a': '=a',
    'd': '=d',
    'g': '=g',
    'c': '=c',
    'f': '=f',
    'B': '=B',
    'E': '=E',
    'A': '=A',
    'D': '=D',
    'G': '=G',
    'C': '=C',
    'F': '=F'
  },
};

// 映射调式名称到简写
Map<String, String> keyToShort = {
  'C Major': 'C',
  'A Minor': 'Am',
  'G Major': 'G',
  'E Minor': 'Em',
  'D Major': 'D',
  'B Minor': 'Bm',
  'A Major': 'A',
  'F# Minor': 'F#m',
  'E Major': 'E',
  'C# Minor': 'C#m',
  'B Major': 'B',
  'G# Minor': 'G#m',
  'F# Major': 'F#',
  'D# Minor': 'D#m',
  'C# Major': 'C#',
  'A# Minor': 'A#m',
  'F Major': 'F',
  'E# Major': 'F',
  'D Minor': 'Dm',
  'Bb Major': 'Bb',
  'A# Major': 'A#',
  'G Minor': 'Gm',
  'Eb Major': 'Eb',
  'D# Major': 'D#',
  'C Minor': 'Cm',
  'Ab Major': 'Ab',
  'G# Major': 'G#',
  'F Minor': 'Fm',
  'Db Major': 'Db',
  'Bb Minor': 'Bbm',
  'Gb Major': 'Gb',
  'Eb Minor': 'Ebm',
  'Cb Major': 'Cb',
  'Ab Minor': 'Abm'
};

// 映射简写到调式名称
Map<String, String> shortToKey = {
  for (var k in keyToShort.keys) keyToShort[k]!: k
};

List<String> convertKeyToTruetone(List<String> notes, String originalKey) {
  var conversionDict = keytoneToTruetone[originalKey] ?? {};
  var truetoneNotes = <String>[];

  for (var note in notes) {
    for (var k in conversionDict.keys) {
      if (note.contains(k)) {
        note = note.replaceAllMapped(
            RegExp(r'''([\-]?)([\^_=]?[A-Ga-gz])([\d,/\'\d]*)'''),
            (match) =>
                '${match.group(1)}${conversionDict[k]}${match.group(3)}');
        break;
      }
    }
    truetoneNotes.add(note);
  }

  return truetoneNotes;
}

List<String> convertTruetoneToKey(List<String> notes, String targetKey) {
  var conversionDict = truetoneToKeytone[targetKey] ?? {};
  var keytoneNotes = <String>[];

  for (var note in notes) {
    for (var k in conversionDict.keys) {
      if (note.contains(k)) {
        note = note.replaceAllMapped(
            RegExp(r'''([\-]?)([\^_=]?[A-Ga-gz])([\d,/\'\d]*)'''),
            (match) =>
                '${match.group(1)}${conversionDict[k]}${match.group(3)}');
        break;
      }
    }
    keytoneNotes.add(note);
  }

  return keytoneNotes;
}

String convertAbcNotation(String abcNotation, String targetKey) {
  var parsed = parseAbc(abcNotation);
  Map<String, String> header = parsed[0];
  var notes = parsed[1];
  var originalKey = header['K'];

  // 转换为真实音符
  var originalKeyLong = shortToKey[originalKey] ?? originalKey;
  var truetoneNotes = convertKeyToTruetone(notes, originalKeyLong!);

  // 转换为目标调式音符
  var targetKeyLong = shortToKey[targetKey] ?? targetKey;
  var keytoneNotes = convertTruetoneToKey(truetoneNotes, targetKeyLong);

  // 修改header中的K项
  header['K'] = keyToShort[targetKeyLong] ?? targetKeyLong;

  // 格式化并输出
  return formatNotes(header, keytoneNotes);
}
