const Map<String, String> en_US = {
  'Prompt Mode': 'Prompt Mode',
  'Create Mode': 'Create Mode',
  'Prompt': 'Prompt',
  'Soft keyboard': 'Soft keyboard',
  'Keyboard Options': 'Keyboard Options',
  'Instrument': 'Instrument',
  'AI Compose': 'AI Compose',
  'Stop Compose': 'Stop Compose',
  'generating tips': 'Please input some notes before generating.',
  'Undo': 'Undo',
  'Reset': 'Reset',
  'Settings': 'Settings',
  'Randomness': 'Randomness',
  'Seed': 'Seed',
  'Auto Chord': 'Auto Chord',
  'Infinite Generation': 'Infinite Generation',
  'Select a directory': 'Select a directory',
  'tips': 'tips',
  'save file success': 'save file success',
  'Export Midi File': 'Export Midi File',
  'Scan BlueTooth Device': 'Scan BlueTooth Device',
  'FeedBack': 'FeedBack',
  'Please input your opinions or suggestions':
      'Please input your opinions or suggestions',
  'Thank you, we have received your suggestions and feedback.':
      'Thank you, we have received your suggestions and feedback.',
  'Submit': 'Submit',
  'Time signature': 'Time signature',
  'Tempo': 'Tempo',
  'show Prompt': 'show Prompt',
  'Connect Midi Keyboard': 'Connect Midi Keyboard',
  'Connect Midi Keyboard tips':
      'Please connect your midi keyboard first. Wireless connection is recommended.',
  'OK': 'OK',
  'Bluetooth Connect': 'Bluetooth Connect',
  'midi keyboard connected': 'midi keyboard connected',
  'Remember Last Option': 'Remember Last Option',
  'Bluetooth unknown': 'Bluetooth unknown',
  'Bluetooth unsupported': 'Bluetooth unsupported',
  'Bluetooth unauthorized': 'Bluetooth unauthorized',
  'Bluetooth poweredOff': 'Bluetooth poweredOff',
  'Version Update': 'Version Update',
  'Cancel': 'Cancel',
  'Update': 'Update',
  'please check network,download fail': 'please check network,download fail',
  'device disconnected': 'device disconnected',
  'device connected': 'device connected',
  'need to open location permission': 'need to open location permission',
  'need to open bluetooth scan permission':
      'need to open bluetooth scan permission',
  'need to open bluetooth connect permission':
      'need to open bluetooth connect permission',
  'Simulate keyboard': 'Simulate keyboard',
  'Midi keyboard': 'Midi keyboard',
  'This content is AI-generated, please carefully discern!':
      'This content is AI-generated, please carefully discern!',
  'User Agreement': 'User Agreement',
  "Please read and agree to our ": 'Please read and agree to our ',
  "user agreement": 'user agreement',
  " and ": ' and ',
  "privacy policy": 'privacy policy',
  " to continue using this application.":
      ' to continue using this application.',
  'Disagree': 'Disagree',
  'Agree': 'Agree',
  "Piano": 'Piano',
  "Violin": 'Violin',
  "Ocarina": 'Ocarina',
  "Cello": 'Cello',
  "Guitar": 'Guitar',
  "Random\nGroove": 'Random\nGroove',
  "Delete": 'Delete',
  "Chord Editing": 'Chord Editing',
  "Time Changing": 'Time Changing',
  "Transpose": 'Transpose',
  "Enter the number of semitones to transpose":
      'Enter the number of semitones to transpose',
  "Please play some notes before randomizing.":
      'Please play some notes before randomizing.',
};
