const Map<String, String> zh_HK = {
  'Prompt Mode': 'Prompt Mode',
  'Create Mode': 'Create Mode',
  'Prompt': 'Prompt',
  'Soft keyboard': 'Soft keyboard',
  'Keyboard Options': 'Keyboard Options',
  'Instrument': 'Instrument',
  'AI Compose': 'AI Compose',
  'Stop Compose': 'Stop Compose',
  'generating tips': 'Please input some notes before generating.',
  'Undo': 'Undo',
  'Reset': 'Reset',
  'Settings': 'Settings',
  'Randomness': 'Randomness',
  'Seed': 'Seed',
  'Auto Chord': 'Auto Chord',
  'Infinite Generation': 'Infinite Generation',
  'Select a directory': 'Select a directory',
  'tips': 'tips',
  'save file success': 'save file success',
  'Export Midi File': 'Export Midi File',
  'Scan BlueTooth Device': 'Scan BlueTooth Device',
  'FeedBack': 'FeedBack',
  'Time signature': 'Time signature',
  'Tempo': 'Tempo',
  'show Prompt': 'show Prompt',
  'Connect Midi Keyboard': 'Connect Midi Keyboard',
  'Connect Midi Keyboard tips':
      'Please connect your midi keyboard first. Wireless connection is recommended.',
  'OK': 'OK',
  'Bluetooth Connect': 'Bluetooth Connect',
  'midi keyboard connected': 'midi keyboard connected',
  'Remember Last Option': 'Remember Last Option',
};
