const Map<String, String> zh_HK = {
  'Prompt Mode': '預設模式',
  'Create Mode': '創作模式',
  'Prompt': '預設旋律',
  'Soft keyboard': '虛擬鍵盤',
  'Keyboard Options': '鍵盤選項',
  'Instrument': '樂器',
  'AI Compose': 'AI作曲',
  'Stop Compose': '停止作曲',
  'generating tips': '請先輸入音符',
  'Undo': '撤銷',
  'Reset': '重置',
  'Settings': '設置',
  'Randomness': '隨機性',
  'Seed': '隨機數種子',
  'Auto Chord': '自動和弦',
  'Infinite Generation': '無限生成',
  'Select a directory': '選擇一個目錄',
  'tips': '提示',
  'save file success': '檔案保存成功',
  'Export Midi File': '匯出Midi檔案',
  'Scan BlueTooth Device': '掃描藍牙裝置',
  'FeedBack': '回饋',
  'Please input your opinions or suggestions': '請輸入您的意見或者建議',
  'Thank you, we have received your suggestions and feedback.':
      '謝謝，我們已經收到您的回饋。',
  'Submit': '提交',
  'Time signature': '拍號',
  'Tempo': '速度',
  'show Prompt': '顯示提示詞',
  'Connect Midi Keyboard': '連接Midi鍵盤',
  'Connect Midi Keyboard tips': 'Midi鍵盤連接方式',
  'OK': '確定',
  'Bluetooth Connect': '藍牙連接',
  'midi keyboard connected': 'Midi鍵盤已連接',
  'Remember Last Option': '記住我的選擇',
  'Bluetooth unknown': '未知的藍牙裝置',
  'Bluetooth unsupported': '藍牙裝置不支援',
  'Bluetooth unauthorized': '藍牙裝置未授權',
  'Bluetooth poweredOff': '請先打開藍牙',
  'Version Update': '版本更新',
  'Cancel': '取消',
  'Update': '更新',
  'please check network,download fail': '下載失敗，請檢查您的網絡連線',
  'device disconnected': '裝置已斷開連接',
  'device connected': '裝置已連接',
  'need to open location permission': '需開啟您的位置權限',
  'need to open bluetooth scan permission': '需開啟您的藍牙掃描權限',
  'need to open bluetooth connect permission': '需開啟您的藍牙連接權限',
  'Simulate keyboard': '虛擬鍵盤',
  'Midi keyboard': 'Midi鍵盤',
  'This content is AI-generated, please carefully discern!': '此內容由AI生成，請仔細甄別！',
  'User Agreement': '用戶協議',
  "Please read and agree to our ": '請閱讀並同意我們的 ',
  "user agreement": '用戶協議',
  " and ": ' 和 ',
  "privacy policy": '隱私政策',
  " to continue using this application.": ' 以繼續使用此應用。',
  'Disagree': '拒絕',
  'Agree': '同意',
  "Piano": '鋼琴',
  "Violin": '小提琴',
  "Ocarina": '陶笛',
  "Cello": '大提琴',
  "Guitar": '吉他',
  "Random\nGroove": '隨機律動',
  "Delete": '刪除',
  "Chord Editing": '編輯和弦',
  "Time Changing": '修改節拍',
  "Transpose": '移調',
  "Enter the number of semitones to transpose": '輸入要移調的半音數量',
  "Please play some notes before randomizing.": '使用隨機律動前請先輸入音符'
};
