const Map<String, String> zh_Hans = {
  'Prompt Mode': '预设模式',
  'Create Mode': '创作模式',
  'Prompt': '预设旋律',
  'Soft keyboard': '软键盘',
  'Keyboard Options': '键盘选项',
  'Instrument': '乐器音效',
  'AI Compose': 'AI作曲',
  'Stop Compose': '停止作曲',
  'generating tips': '请先输入音符',
  'Undo': '撤销',
  'Reset': '重置',
  'Settings': '设置',
  'Randomness': '随机性',
  'Seed': '种子',
  'Auto Chord': '自动和弦',
  'Infinite Generation': '无限生成',
  'Select a directory': '选择一个目录',
  'tips': '提示',
  'save file success': '文件保存成功',
  'Export Midi File': '导出Midi文件',
  'Scan BlueTooth Device': '扫描蓝牙设备',
  'FeedBack': '反馈',
  'Please input your opinions or suggestions': '请输入你的意见或者建议',
  'Thank you, we have received your suggestions and feedback.':
      '谢谢，我们已经收到你的意见和建议',
  'Submit': '提交',
  'Time signature': '拍号',
  'Tempo': '速度',
  'show Prompt': '显示预设词',
  'Connect Midi Keyboard': '连接Midi键盘',
  'Connect Midi Keyboard tips': '请先连接你的Midi键盘. 推荐使用蓝牙连接Midi键盘.',
  'OK': '确定',
  'Bluetooth Connect': '蓝牙连接',
  'midi keyboard connected': 'Midi键盘已连接',
  'Remember Last Option': '记住上次选择',
  'Bluetooth unknown': '蓝牙未知',
  'Bluetooth unsupported': '蓝牙不支持',
  'Bluetooth unauthorized': '蓝牙没有授权',
  'Bluetooth poweredOff': '请先打开蓝牙',
  'Version Update': '版本更新',
  'Cancel': '取消',
  'Update': '更新',
  'please check network,download fail': '下载失败，请检查您的网络连接',
  'device disconnected': '设备已断开连接',
  'device connected': '设备已连接',
  'need to open location permission': '需打开您的位置权限',
  'need to open bluetooth scan permission': '需打开您的蓝牙搜寻权限',
  'need to open bluetooth connect permission': '需打开您的蓝牙连接权限',
  'Simulate keyboard': '软键盘',
  'Midi keyboard': 'Midi键盘',
  'This content is AI-generated, please carefully discern!': '此内容由AI生成，请仔细甄别！',
  'User Agreement': '用户协议',
  "Please read and agree to our ": '请阅读和同意我们的 ',
  "user agreement": '用户协议',
  " and ": ' 和 ',
  "privacy policy": '隐私政策',
  " to continue using this application.": ' 继续使用该应用.',
  'Disagree': '拒绝',
  'Agree': '同意',
  "Piano": '钢琴',
  "Violin": '小提琴',
  "Ocarina": '陶笛',
  "Cello": '大提琴',
  "Guitar": '吉他',
  "Random\nGroove": '随机\n律动',
  "Delete": '删除',
  "Chord Editing": '编辑和弦',
  "Time Changing": '修改节拍',
  "Transpose": '移调',
  "Enter the number of semitones to transpose": '输入要移调的半音数量',
  "Please play some notes before randomizing.": '请先演奏一些音符再进行随机律动.',
};
