name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-version
      id: get_version
      run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  # windows-x64-vs2022:
  #   needs: [setup]
  #   runs-on: windows-latest
  #   env:
  #     VERSION: ${{ needs.setup.outputs.VERSION }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Setup Flutter SDK
  #       uses: flutter-actions/setup-flutter@v3
  #       with:
  #         channel: stable
  #     - name: Install dependencies
  #       run: |
  #         cd rwkvmusic
  #         flutter pub get
  #     - name: Build Windows x64
  #       run: |
  #         cd rwkvmusic
  #         flutter build windows
  #     - name: Package Windows x64
  #       run: |
  #         C:\msys64\usr\bin\wget.exe https://uwuhome.momosan.cc:3000/molly/rwkvmusic-models/releases/download/master/release-windows-x64.zip
  #         7z x release-windows-x64.zip
  #         cd rwkvmusic
  #         mkdir build/windows/x64/runner/Release/lib/
  #         mkdir build/windows/x64/runner/Release/lib/fastmodel
  #         Copy-Item -Path ../runtime/* -Destination build/windows/x64/runner/Release/lib/fastmodel -Recurse
  #         Copy-Item -Path ../weights/* -Destination build/windows/x64/runner/Release/lib/fastmodel -Recurse
  #         cd build/windows/x64/runner/
  #         7z a -r ../../../../../rwkvmusic-windows-x64-${{env.VERSION}}.zip Release
  #     - name: Upload Windows x64
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: rwkvmusic-windows-x64-${{env.VERSION}}
  #         path: rwkvmusic-windows-x64-${{env.VERSION}}.zip

  windows-arm64-vs2022:
    needs: [setup]
    # 使用官方为公共仓库提供的 Windows ARM64 运行器标签
    runs-on: windows-11-arm
    env:
      VERSION: ${{ needs.setup.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 Flutter SDK 环境，指定 arm64 架构
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 或者指定你需要的 channel, e.g., 'beta'
          architecture: arm64

      # (可选，但推荐) 安装 Visual Studio 构建工具
      # 虽然 runner 镜像可能包含一些工具，但显式安装可以确保所需组件存在
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: 'latest' # 或者指定具体版本
          # 添加构建 Windows 应用所需的组件，根据你的项目需求调整
          msbuild-architecture: 'arm64'
          components: 'Microsoft.VisualStudio.Component.VC.Tools.ARM64;Microsoft.VisualStudio.Component.Windows10SDK.19041' # 示例，可能需要调整

      # (可选) 安装 7-Zip
      # runner 镜像可能不包含 7-Zip，如果打包步骤需要它，则安装
      - name: Install 7-Zip
        # 使用 choco (通常在 Windows runner 上可用) 或其他方式安装
        run: choco install 7zip -y --force

      - name: Install dependencies
        run: |
          cd rwkvmusic
          flutter pub get

      - name: Build Windows arm64
        run: |
          cd rwkvmusic
          # 明确指定目标平台为 windows-arm64
          flutter build windows --target-platform=windows-arm64

      - name: Package Windows arm64
        run: |
          Invoke-WebRequest -Uri https://uwuhome.momosan.cc:3000/molly/rwkvmusic-models/releases/download/master/release-windows-arm64.zip -OutFile release-windows-arm64.zip
          # 确保 7z 命令在 PATH 中，或者提供完整路径
          # 如果 choco 安装了，通常会自动添加到 PATH
          7z x release-windows-arm64.zip
          cd rwkvmusic
          Copy-Item -Path ../runtime/* -Destination build/windows/arm64/runner/Release/ -Recurse
          Copy-Item -Path ../weights/* -Destination build/windows/arm64/runner/Release/lib/fastmodel -Recurse
          cd build/windows/arm64/runner/
          7z a -r ../../../../../rwkvmusic-windows-arm64-${{env.VERSION}}.zip Release

      - name: Upload Windows arm64
        uses: actions/upload-artifact@v4
        with:
          name: rwkvmusic-windows-arm64-${{env.VERSION}}
          path: rwkvmusic-windows-arm64-${{env.VERSION}}.zip
  
  # android:
  #   needs: [setup]
  #   runs-on: ubuntu-latest
  #   env:
  #     VERSION: ${{ needs.setup.outputs.VERSION }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set Up Java
  #       uses: actions/setup-java@v3.12.0
  #       with:
  #         distribution: 'oracle'
  #         java-version: '17'
  #     - name: Setup Flutter SDK
  #       uses: flutter-actions/setup-flutter@v3
  #       with:
  #         channel: stable
  #     - name: Install dependencies
  #       run: |
  #         cd rwkvmusic
  #         flutter pub get
  #     - name: Build APK
  #       run: |
  #         cd rwkvmusic
  #         flutter build apk --release
  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: rwkvmusic-android-${{env.VERSION}}
  #         path: |
  #           rwkvmusic/build/app/outputs/flutter-apk/app-release.apk